version: '3.3'

services: 
  web: 
    image: ${DOCKER_USER_ID}/ex4
    build: .
  production:
    image: ${DOCKER_USER_ID}/ex4:${BUILD_NUMBER}
    volumes:
    - .:/code
    command: main.py
    ports:
    - "80:85"
      